name: deploy 

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
